import os
import json
import uuid
import tempfile
from datetime import datetime, timezone
from fastapi import FastAPI, File, UploadFile, HTTPException
from fastapi.responses import JSONResponse
from fastapi.middleware.cors import CORSMiddleware
from dotenv import load_dotenv

# Groq
from groq import Groq
# OpenAI
from openai import OpenAI

# ReportLab for PDF
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_JUSTIFY

# AWS SDK
import boto3
from botocore.exceptions import ClientError

# SQLAlchemy for RDS (PostgreSQL)
from sqlalchemy import create_engine, Column, Integer, String, DateTime
from sqlalchemy.orm import declarative_base, sessionmaker

load_dotenv(dotenv_path=os.path.join(os.path.dirname(__file__), '..', '.env'))

app = FastAPI(title="AI Scribe Backend (DPDP Compliant)")

# Allow CORS for the frontend
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# --- AWS configuration ---
AWS_REGION = "ap-south-1"  # Mumbai Region for DPDP Compliance
S3_BUCKET_NAME = os.getenv("S3_BUCKET_NAME", "sumedhaa-medical-notes")

# --- 1. AWS Secrets Manager ---
def get_secret(secret_name):
    # For local development, use .env first if available
    local_secret = os.getenv(secret_name)
    if local_secret:
        return local_secret
        
    # In production (App Runner), fetch from Secrets Manager
    session = boto3.session.Session()
    client = session.client(service_name='secretsmanager', region_name=AWS_REGION)
    
    try:
        get_secret_value_response = client.get_secret_value(SecretId="sumedhaa-api-keys")
        secret = json.loads(get_secret_value_response['SecretString'])
        return secret.get(secret_name)
    except ClientError as e:
        print(f"Error retrieving secret from AWS: {e}")
        return None

# Initialize API Clients using Secrets Manager
groq_api_key = get_secret("GROQ_API_KEY")
groq_client = Groq(api_key=groq_api_key) if groq_api_key else None

openai_api_key = get_secret("OPENAI_API_KEY")
openai_client = OpenAI(api_key=openai_api_key) if openai_api_key else None


# --- 2. Amazon RDS (PostgreSQL) Setup ---
# Use environment variable for DB connection, fallback to sqlite for local dev if not provided
DATABASE_URL = os.getenv("DATABASE_URL", "sqlite:///./local_audit.db")

engine = create_engine(DATABASE_URL)
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)
Base = declarative_base()

class AuditLog(Base):
    __tablename__ = "audit_logs"
    id = Column(Integer, primary_key=True, index=True)
    action = Column(String, index=True)
    details = Column(String)
    timestamp = Column(DateTime, default=lambda: datetime.now(timezone.utc))

# Create tables
try:
    Base.metadata.create_all(bind=engine)
except Exception as e:
    print(f"Warning: Could not connect to database on startup (will retry on demand): {e}")

def log_audit_action(action: str, details: str):
    """Log an action to the PostgreSQL database for DPDP compliance."""
    db = SessionLocal()
    try:
        log = AuditLog(action=action, details=details)
        db.add(log)
        db.commit()
    except Exception as e:
        print(f"Failed to write audit log: {e}")
    finally:
        db.close()


# --- Routes ---

@app.post("/api/process_audio")
async def process_audio(audio: UploadFile = File(...)):
    if not groq_client or not openai_client:
        raise HTTPException(status_code=500, detail="API Keys for Groq or OpenAI are missing.")
        
    try:
        audio_bytes = await audio.read()
            
        transcription = groq_client.audio.transcriptions.create(
            file=("audio.wav", audio_bytes),
            model="whisper-large-v3",
            prompt="Aapko kaisa lag raha hai? I have been feeling thoda weakness and fever since kal raat. Take this paracetamol tablet din mein teen baar.",
            temperature=0,
            response_format="verbose_json",
        )
        
        full_transcript = transcription.text
        if not full_transcript:
            raise Exception("No transcription generated by Groq.")
        
        prompt = f"""
        You are an expert medical AI assistant.
        Given the raw medical consultation transcript below, perform two tasks:
        1. Format the text as a conversation with clear speaker labels (infer who is the Doctor and who is the Patient). 
           CRITICAL: Translate any Hindi or non-English text entirely into professional English. The output transcript MUST be 100% in English.
        2. Create a structured SOAP note based on the consultation, also completely in English.
        
        Return the result strictly as a JSON object with this exact structure:
        {{
            "transcript": [
                {{"speaker": "Doctor", "text": "..."}},
                {{"speaker": "Patient", "text": "..."}}
            ],
            "soap_note": {{
                "subjective": "...",
                "objective": "...",
                "assessment": "...",
                "plan": "..."
            }}
        }}
        
        Raw Transcript:
        {full_transcript}
        """
        
        oa_response = openai_client.chat.completions.create(
            model="gpt-4o",
            response_format={ "type": "json_object" },
            messages=[
                {"role": "system", "content": "You are a helpful assistant designed to output strict JSON."},
                {"role": "user", "content": prompt}
            ],
            temperature=0
        )
        
        content = oa_response.choices[0].message.content
        if not content:
            raise Exception("No content returned from OpenAI.")
        result_json = json.loads(content)
        
        # Log to RDS for DPDP Compliance
        log_audit_action("AUDIO_PROCESSED", "Processed an audio consultation and generated SOAP note.")
        
        return JSONResponse({
            "transcript": result_json.get("transcript", []),
            "soap_note": result_json.get("soap_note", {})
        })
            
    except Exception as e:
        log_audit_action("ERROR", f"Failed processing audio: {str(e)}")
        raise HTTPException(status_code=500, detail=str(e))


@app.post("/api/export_pdf")
async def export_pdf(data: dict):
    """
    Accepts the finalized SOAP note, generates a PDF, and uploads it to Amazon S3.
    Returns a pre-signed URL to download the PDF securely.
    """
    try:
        soap_note = data.get("soap_note", {})
        
        # 1. Generate PDF locally in a temp file
        temp_pdf_path = os.path.join(tempfile.gettempdir(), f"soap_note_{uuid.uuid4().hex}.pdf")
        
        doc = SimpleDocTemplate(temp_pdf_path, pagesize=letter)
        styles = getSampleStyleSheet()
        
        title_style = styles['Heading1']
        title_style.alignment = 1 
        
        heading_style = styles['Heading2']
        body_style = ParagraphStyle(
            'Body', parent=styles['Normal'], spaceAfter=14, alignment=TA_JUSTIFY
        )
        
        story = [Paragraph("Clinical SOAP Note", title_style), Spacer(1, 12)]
        
        sections = [
            ("Subjective", soap_note.get("subjective", "")),
            ("Objective", soap_note.get("objective", "")),
            ("Assessment", soap_note.get("assessment", "")),
            ("Plan", soap_note.get("plan", ""))
        ]
        
        for title, content in sections:
            story.append(Paragraph(title, heading_style))
            clean_content = str(content).replace('\n', '<br/>')
            story.append(Paragraph(clean_content, body_style))
            
        doc.build(story) # type: ignore
        
        # 2. Upload to Amazon S3
        s3_client = boto3.client('s3', region_name=AWS_REGION)
        s3_file_name = f"soap_notes/{uuid.uuid4().hex}.pdf"
        
        s3_client.upload_file(temp_pdf_path, S3_BUCKET_NAME, s3_file_name)
        
        # 3. Generate a pre-signed URL for the user to download (valid for 1 hour)
        presigned_url = s3_client.generate_presigned_url(
            'get_object',
            Params={'Bucket': S3_BUCKET_NAME, 'Key': s3_file_name},
            ExpiresIn=3600
        )
        
        # Clean up local temp file to satisfy Zero-Disk footprint on EC2/AppRunner
        if os.path.exists(temp_pdf_path):
            os.remove(temp_pdf_path)
            
        # Log to RDS
        log_audit_action("PDF_EXPORTED", f"Exported SOAP note to S3: {s3_file_name}")
        
        return JSONResponse({"download_url": presigned_url})
        
    except Exception as e:
        log_audit_action("ERROR", f"Failed exporting PDF: {str(e)}")
        raise HTTPException(status_code=500, detail=str(e))

if __name__ == "__main__":
    import uvicorn
    uvicorn.run("app:app", host="0.0.0.0", port=8000, reload=True)
