import os
import json
import uuid
import tempfile
from fastapi import FastAPI, File, UploadFile, HTTPException
from fastapi.responses import FileResponse, JSONResponse
from fastapi.middleware.cors import CORSMiddleware
from dotenv import load_dotenv

# Groq
from groq import Groq

# OpenAI
from openai import OpenAI

# ReportLab for PDF
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_JUSTIFY

# Load environment variables from the parent directory's .env file
load_dotenv(dotenv_path=os.path.join(os.path.dirname(__file__), '..', '.env'))

app = FastAPI(title="AI Scribe Backend")

# Allow CORS for the frontend
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Initialize API Clients
groq_api_key = os.getenv("GROQ_API_KEY") or os.getenv("GROK_API_KEY")
if not groq_api_key:
    print("Warning: GROQ_API_KEY not found in environment.")
groq_client = Groq(api_key=groq_api_key) if groq_api_key else None

openai_api_key = os.getenv("OPENAI_API_KEY")
if not openai_api_key:
    print("Warning: OPENAI_API_KEY not found in environment.")
openai_client = OpenAI(api_key=openai_api_key) if openai_api_key else None


@app.post("/api/process_audio")
async def process_audio(audio: UploadFile = File(...)):
    """
    1. Receives audio file
    2. Sends to Groq (whisper-large-v3) with Hinglish prompt
    3. Sends raw transcript to OpenAI for Diarization AND SOAP Note generation
    4. Returns everything to the frontend
    """
    if not groq_client or not openai_client:
        raise HTTPException(status_code=500, detail="API Keys for Groq or OpenAI are missing.")
        
    try:
        # Read audio directly into RAM (Zero-Disk DPDP Compliance)
        audio_bytes = await audio.read()
            
        # 1. Groq Transcription (whisper-large-v3 with Hinglish Prompt)
        transcription = groq_client.audio.transcriptions.create(
            file=("audio.wav", audio_bytes),
            model="whisper-large-v3",
            prompt="Aapko kaisa lag raha hai? I have been feeling thoda weakness and fever since kal raat. Take this paracetamol tablet din mein teen baar.",
            temperature=0,
            response_format="verbose_json",
        )
        
        full_transcript = transcription.text
        if not full_transcript:
            raise Exception("No transcription generated by Groq.")
        
        # 2. OpenAI Diarization & SOAP Note Generation
        prompt = f"""
        You are an expert medical AI assistant.
        Given the raw medical consultation transcript below, perform two tasks:
        1. Format the text as a conversation with clear speaker labels (infer who is the Doctor and who is the Patient). 
           CRITICAL: Translate any Hindi or non-English text entirely into professional English. The output transcript MUST be 100% in English.
        2. Create a structured SOAP note based on the consultation, also completely in English.
        
        Return the result strictly as a JSON object with this exact structure:
        {{
            "transcript": [
                {{"speaker": "Doctor", "text": "..."}},
                {{"speaker": "Patient", "text": "..."}}
            ],
            "soap_note": {{
                "subjective": "...",
                "objective": "...",
                "assessment": "...",
                "plan": "..."
            }}
        }}
        
        Raw Transcript:
        {full_transcript}
        """
        
        oa_response = openai_client.chat.completions.create(
            model="gpt-4o",
            response_format={ "type": "json_object" },
            messages=[
                {"role": "system", "content": "You are a helpful assistant designed to output strict JSON."},
                {"role": "user", "content": prompt}
            ],
            temperature=0
        )
        
        content = oa_response.choices[0].message.content
        if not content:
            raise Exception("No content returned from OpenAI.")
            
        result_json = json.loads(content)
        
        return JSONResponse({
            "transcript": result_json.get("transcript", []),
            "soap_note": result_json.get("soap_note", {})
        })
            
    except Exception as e:
        print(f"Error processing audio: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@app.post("/api/export_pdf")
async def export_pdf(data: dict):
    """
    Accepts the finalized SOAP note and generates a PDF file for download.
    """
    try:
        soap_note = data.get("soap_note", {})
        
        temp_pdf_path = os.path.join(tempfile.gettempdir(), f"soap_note_{uuid.uuid4().hex}.pdf")
        
        doc = SimpleDocTemplate(temp_pdf_path, pagesize=letter)
        styles = getSampleStyleSheet()
        
        title_style = styles['Heading1']
        title_style.alignment = 1 
        
        heading_style = styles['Heading2']
        
        body_style = ParagraphStyle(
            'Body',
            parent=styles['Normal'],
            spaceAfter=14,
            alignment=TA_JUSTIFY
        )
        
        story = []
        
        story.append(Paragraph("Clinical SOAP Note", title_style))
        story.append(Spacer(1, 12))
        
        sections = [
            ("Subjective", soap_note.get("subjective", "")),
            ("Objective", soap_note.get("objective", "")),
            ("Assessment", soap_note.get("assessment", "")),
            ("Plan", soap_note.get("plan", ""))
        ]
        
        for title, content in sections:
            story.append(Paragraph(title, heading_style))
            clean_content = content.replace('\n', '<br/>')
            story.append(Paragraph(clean_content, body_style))
            
        doc.build(story)
        
        return FileResponse(
            temp_pdf_path, 
            media_type='application/pdf', 
            filename='SOAP_Note.pdf'
        )
        
    except Exception as e:
        print(f"Error exporting PDF: {e}")
        raise HTTPException(status_code=500, detail=str(e))

if __name__ == "__main__":
    import uvicorn
    uvicorn.run("app:app", host="0.0.0.0", port=8000, reload=True)
